version: '3'
services:
  api:
    build: ./server/
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    links:
      - mongo
      - graph
  app:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    links:
      - api
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
  graph:
    image: neo4j
    volumes:
      - $NEO4J_HOME/data:/data
      - $NEO4J_HOME/logs:/logs
    ports:
      - "7687:7687"
      - "7474:7474"
