version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - app
  api:
    build: ./server/
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    links:
      - mongo
      - graph
  app:
    build: ./client/
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    links:
      - api
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - $MONGO_HOME/db:/data/db
    ports:
      - "27017:27017"
  graph:
    image: neo4j
    container_name: graph
    volumes:
      - $NEO4J_HOME/data:/data
      - $NEO4J_HOME/logs:/logs
    ports:
      - "7687:7687"
      - "7474:7474"
